# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChannelizeUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ChannelizeAPI', '>= 4.20.8'
  #$awsVersion = '2.9.3'
  #pod 'AWSMobileClient', $awsVersion
  #pod 'AWSIoT', $awsVersion
  #pod 'Alamofire', '4.8.2'
  #pod 'AlamofireObjectMapper', '5.2.0'
  pod 'ChannelizeCall', '>= 4.20.8'
  pod 'InputBarAccessoryView', '4.2.2'
  pod 'SDWebImageFLPlugin'
  pod 'DifferenceKit'
  pod 'MaterialComponents/ProgressView'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'ReachabilitySwift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
