source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ChannelizeUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ChannelizeAPI', '>= 4.20.10'
  pod 'ChannelizeCall', '>= 4.20.8'
  pod 'InputBarAccessoryView', '4.2.2'
  pod 'SDWebImageFLPlugin'
  pod 'DifferenceKit'
  pod 'MaterialComponents/ProgressView'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'ReachabilitySwift'
  pod 'VirgilE3Kit'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if target.name == "VirgilE3Kit"
            config.build_settings['SWIFT_VERSION'] = '5.1'
          else
            config.build_settings['SWIFT_VERSION'] = '4.2'
          end
        end
    end
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

