# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChannelizeUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   $awsVersion = '2.9.3'
   pod 'AWSMobileClient', $awsVersion
   pod 'AWSIoT', $awsVersion
   pod 'InputBarAccessoryView', '4.2.2'
   pod 'Alamofire', '4.8.2'
   pod 'AlamofireObjectMapper', '5.2.0'
   pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'
   pod 'SDWebImageFLPlugin'
   pod 'MaterialComponents'
   pod 'DifferenceKit'
   pod 'AgoraRtcEngine_iOS', '2.9.0'
   pod 'ChannelizeUI', :git => 'https://github.com/ChannelizeIO/Channelize-iOS-UI-SDK.git'

  # Pods for ChannelizeUI

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
